### PR TITLE
pkg(com.google.android.apps.messaging): add notice for Unihertz users

### PR DESCRIPTION
**Pull request by AnonymousWP**

### CODE REVIEW

**Comment by schbrns** [comment]
Is this really an issue? Those phones are bricks as far as I can read, Verizon Unihertz phones can't even SMS/MMS anymore.

**Comment by AnonymousWP** [comment]
> Is this really an issue? Those phones are bricks as far as I can read, Verizon Unihertz phones can't even SMS/MMS anymore.

Well, looking to the linked issue, it apparently is. It's not really an issue for all users, which is why `removal` remains the same but an additional note is added for Unihertz users. The fact that those Unihertz phones are quickly bricking is an issue apart from that in my opinion.

**Comment by schbrns** [comment]
Messages has been due for an upgrade to Expert, along with everything else I've been targeting.

Messages, historically, has affected: Banking verification, receiving SMS OTP, RCS capabilities, etc.

Wouldn't need anymore device-specific notes anymore then.

**Comment by schbrns** [comment]
I hear what you're saying when you say I should open a PR to discuss it but I'll save us both the time and provide it right here, along with justification.

Jutification: 
Simply the REMOVAL AND REINSTALLATION of Messages,
breaks CORE FUNCTIONALITY on MOST CARRIERS/OEMS GLOBALLY, 
to the point of needing A FACTORY RESET, 
and the only workaround is to KEEP IT INSTALLED (REMOVAL: UNSAFE???),
alongside a different SMS app that you use.

`"description": "Google Messages (https://play.google.com/store/apps/details?id=com.google.android.apps.messaging)\nSMS and RCS app.\nNOTE: Possibly a global dependency for SMS, MMS, RCS, OTP, and other services/verifications.\nWARNING: Once disabled/uninstalled, even if reinstalled, a factory reset may be required to re-obtain full functionality."`

That's 🔥 right?

**Comment by schbrns** [comment]
This is a public PR. 💀 Thought it was internal. My above comment is NOT how to speak to a contributor.

**Comment by AnonymousWP** [comment]
> I hear what you're saying when you say I should open a PR to discuss it but I'll save us both the time and provide it right here, along with justification.
> 
> Jutification: Simply the REMOVAL AND REINSTALLATION of Messages, breaks CORE FUNCTIONALITY on MOST CARRIERS/OEMS GLOBALLY, to the point of needing A FACTORY RESET, and the only workaround is to KEEP IT INSTALLED (REMOVAL: UNSAFE???), alongside a different SMS app that you use.
> 
> `"description": "Google Messages (https://play.google.com/store/apps/details?id=com.google.android.apps.messaging)\nSMS and RCS app.\nNOTE: Possibly a global dependency for SMS, MMS, RCS, OTP, and other services/verifications.\nWARNING: Once disabled/uninstalled, even if reinstalled, a factory reset may be required to re-obtain full functionality."`
> 
> That's 🔥 right?

Ah okay, didn't know this applies to many other OEMs as well (to the point you need a factory reset). Haven't seen it before, nor other people reporting it. 😄 Wonder why nobody reported breaking core functionality and needing a factory reset then.

**Comment by schbrns** [comment]
> > I hear what you're saying when you say I should open a PR to discuss it but I'll save us both the time and provide it right here, along with justification.
> > Jutification: Simply the REMOVAL AND REINSTALLATION of Messages, breaks CORE FUNCTIONALITY on MOST CARRIERS/OEMS GLOBALLY, to the point of needing A FACTORY RESET, and the only workaround is to KEEP IT INSTALLED (REMOVAL: UNSAFE???), alongside a different SMS app that you use.
> > `"description": "Google Messages (https://play.google.com/store/apps/details?id=com.google.android.apps.messaging)\nSMS and RCS app.\nNOTE: Possibly a global dependency for SMS, MMS, RCS, OTP, and other services/verifications.\nWARNING: Once disabled/uninstalled, even if reinstalled, a factory reset may be required to re-obtain full functionality."`
> > That's 🔥 right?
> 
> Ah okay, didn't know this applies to many other OEMs as well (to the point you need a factory reset). Haven't seen it before, nor other people reporting it. 😄 Wonder why nobody reported breaking core functionality and needing a factory reset then.

To the point of needing factory reset, probably not consistently, but definitely between certain OS subversions. 
But also, I say that under the assumption that this type of thing is rarely ever isolated to one device/carrier/OEM. 
It's almost always spread in a patterned way. 
I think it may be a little dramatic of a description but it blankets what Google is doing with their Messages app better, which is too much. 
It's a form of phone number verification now, not an SMS/RCS app. 😦

**Review by schbrns — APPROVED** [review]

**Pull request merged**
