### PR TITLE
docs(readme): add more distros to ADB install guide and some minor changes

### PR DESCRIPTION
**Pull request by AlbydST**
Added instructions on how to install ADB on PCLinuxOS / Vine Linux / ALT Linux, Solus, Void and OpenWrt Bases and did some minor changes.

### CODE REVIEW

**Comment by adhirajsinghchauhan** [comment]
In the interest of cleaning it up, imo it would be better to just state the package name (`android-tools` etc.) instead of separate commands per distro group. Linux users are aware of which command they'd need to use to install something from their default package managers.

Let's see what others have to say about it.

**Comment by AnonymousWP** [comment]
I agree, because where's the limit? At some point we may have many lines that just use a different package manager as part of the command. And as Adhiraj said: you may expect that Linux users know how to install `android-tools` lol.

**Comment by Frigyes06** [comment]
Who would want to use UAD on OpenWrt based machines? Does it even have a DE/WM

**Comment by Frigyes06** [comment]
Would it maybe make more sense to have the most widespread package managers in the readme, and a link to the wiki where we could have all the other distros?

**Comment by AnonymousWP** [comment]
> Would it maybe make more sense to have the most widespread package managers in the readme, and a link to the wiki where we could have all the other distros?

But how are we going to decide what's a widespread package manager and what isn't? That could be bound to subjectivity.

**Comment by Frigyes06** [comment]
> But how are we going to decide what's a widespread package manager and what isn't? That could be bound to subjectivity.

There are some clear popular/unpopular daily use distros. Like, how many people have you seen walking around with OpenWrt on their laptop?

https://survey.stackoverflow.co/2023/?ref=itsfoss.com#section-most-popular-technologies-operating-system

This survey shows some clearly popular distros, which would probably be Ubuntu, Debian and Arch.

**Comment by AnonymousWP** [comment]
> > But how are we going to decide what's a widespread package manager and what isn't? That could be bound to subjectivity.
> 
> There are some clear popular/unpopular daily use distros. Like, how many people have you seen walking around with OpenWrt on their laptop?
> 
> https://survey.stackoverflow.co/2023/?ref=itsfoss.com#section-most-popular-technologies-operating-system
> 
> This survey shows some clearly popular distros, which would probably be Ubuntu, Debian and Arch.

But, like Adhiraj said: those specific Linux-distro users are aware of which command they'd need to use to install something from their default package managers, so it would only make the README longer imo.

**Comment by Frigyes06** [comment]
How about we move all install guides to the wiki?

**Comment by AnonymousWP** [comment]
Doesn't that only move the 'problem' to somewhere else though? Also, I don't think it fits the use-case for a wiki, see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#wikis.

Let's just drop it and use something like

> Install the Android Platform Tools (`android-tools`) with the by you used package manager.

**Comment by AnonymousWP** [comment]
@Frigyes06 Please follow-up on this.

**Comment by AnonymousWP** [comment]
No longer useful as we moved documentation, but I made some changes https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/Getting-started/_history.

**Pull request closed without merging**
