### PR TITLE
feat(ui): "iconify" Settings button

### PR DESCRIPTION
**Pull request by edgy-b**
- turned Settings button into button with icon

Tooltip can be added, let me know. Don't think gear icon can be mistaken for something else than settings

Made window size smaller. According to this issue https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/69

### CODE REVIEW

**Review by adhirajsinghchauhan — COMMENTED** [review]
How was the TTF regenerated? Did you import `icons.json` into [icomoon](https://icomoon.io/app/#/select), then select this?
image

**Comment by edgy-b** [comment]
> How was the TTF regenerated? Did you import `icons.json` into [icomoon](https://icomoon.io/app/#/select), then select this? image

Yes, imported. But I added Feathered and chosen different icon. Probably should have updated json file also
image

**Review by adhirajsinghchauhan — CHANGES_REQUESTED** [review]
Adding a new icon pack and changing existing icons is out of scope, and is unnecessary. For now, please keep within the icon packs we already have as part of the JSON.

We can discuss internally if changing is required, though I don't see any reason why we would need to.

**Comment by edgy-b** [comment]
> Adding a new icon pack and changing existing icons is out of scope, and is unnecessary. For now, please keep within the icon packs we already have as part of the JSON.
> 
> We can discuss internally if changing is required, though I don't see any reason why we would need to.

Ok, reverted back

**Review by adhirajsinghchauhan — APPROVED** [review]

**Pull request merged**
