### PR TITLE
test(ci): invalid json file IGNORE PR, for testing purposes only

### PR DESCRIPTION
**Pull request by edgy-b**

### CODE REVIEW

**Comment by AnonymousWP** [comment]
Converting this PR to draft, as it's still work in progress.

**Comment by Frigyes06** [comment]
Run cargo test on json changes. It'll fail if the json is messed up.

**Comment by AnonymousWP** [comment]
Any updates on this?

**Comment by AnonymousWP** [comment]
@edgy-b See above.

**Comment by AnonymousWP** [comment]
Superseded by https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/446.

**Pull request closed without merging**
