### PR TITLE
feat: add checksum making commands

### LINKED ISSUE #66: Checksum for new releases
Have you ever thought about adding sha256 checksum for at least the ` uad_gui-linux ` and ` uad_gui-windows.exe ` binaries when releasing a new tag?
It'd be useful that users of UAD can verify that the binary wasn't tampered with or somehow corrupted during the download.

### PR DESCRIPTION
**Pull request by Frigyes06**
Fixes #66.

### CODE REVIEW

**Comment by Frigyes06** [comment]
Well that did not work. Also the action runners don';t have sha256sum

**Comment by Frigyes06** [comment]
Woah! You did it!

**Review by lavafroth — APPROVED** [review]
I separated the workflows to run for windows which only has the .exe file and others (linux and mac) which have the .tar.gz file.

**Comment by lavafroth** [comment]
If you wanna make some more changes, feel free to. Otherwise, we can merge this!

**Comment by adhirajsinghchauhan** [comment]
Would be better to have them as `.sha256` instead of `.txt` or `-checksum`. It's good (and somewhat common) practice to name them explicitly.

**Pull request merged**
