### PR TITLE
style: remove redundant spaces and fix misc typos

### PR DESCRIPTION
**Pull request by AnonymousWP**
This makes it look more neat. Putting spaces between colons look ugly and is probably done by 0x192. It's common for French people to put spaces between colons and exclamation marks etc.

---

Not sure what label to assign.

### CODE REVIEW

**Review by adhirajsinghchauhan — DISMISSED** [review]
LGTM, but if there's anything else you've spotted, might as well include it in this PR

**Comment by AnonymousWP** [comment]
Re-requesting your review as I pushed two new commits, while 1 introduces a minor change.

**Comment by AnonymousWP** [comment]
Seems like dashes are not accepted? Fails at line 38, which is this commit: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/399/commits/d7eb48657f24b0966908f7101064fa908e0b4555.

**Comment by adhirajsinghchauhan** [comment]
> Seems like dashes are not accepted? Fails at line 38, which is this commit: [d7eb486](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/commit/d7eb48657f24b0966908f7101064fa908e0b4555). I'll take a look again later.

It's telling you to rewrite that line to ensure it's within the line-length limit, which is I think 90 (or 100?)
```diff
-        let uad_list_text = text(format!("UAD-ng package list: v{}", date.format("%Y%m%d"))).width(250);
+        let uad_list_text =
+            text(format!("UAD-ng package list: v{}", date.format("%Y%m%d"))).width(250);
```

You could install [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) to have it do it automatically. Just make sure you don't commit Cargo.lock changes, because that extension, as part of its process, also bumps deps.

Otherwise just do it manually as suggested in the failure log above.

**Comment by Frigyes06** [comment]
image
good enough?

**Review by Frigyes06 — APPROVED** [review]

**Pull request merged**
