### PR TITLE
ci: edit checksum artifact paths to allow automatic check

### LINKED ISSUE #270: checking sha256 won't work automatically because of file path
Most software which is shipped with checksums to verify that it hasn't been tampered with can be verified with these steps (on debian-based distros, but similar for different ones):
1. Download binary `imaginary-bin` and `imaginary-bin-sha256.txt`
2. sha256sum imaginary-bin
3. sha256sum --check imaginary-bin-sha256.txt

Which will result in `imaginary-bin: OK` if sums match, but won't work for uad-ng. 

1. sha256sum uad-ng-linux
2. sha256sum --check uad-ng-linux-checksum

Gives this output:
```
sha256sum: bin/uad-ng-linux: No such file or directory
bin/uad-ng-linux: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
```

Most likely because `uad-ng-linux-checksum` has following structure:

```
<hash> bin/uad-ng-linux
```

File paths don't match as we can see: `uad-ng-linux` != `bin/uad-ng-linux`. Of course It can still be verified, but it's annoying not being able to use the in-built method..

Fixing this is easy (just editing the CI). Feel free to assign me and I can do it in the upcoming days.

### PR DESCRIPTION
**Pull request by jxdv**
Closes #270.

All checksums (except windows) can now be verified using standard way with sha256sum utility:

1. `sha256sum <binary>`
2. `sha256sum --check <binary>-checksum`
3. `<binary>: OK`

### CODE REVIEW

**Comment by jxdv** [comment]
I realized that windows has different line ending from unix systems and that's why I couldn't automatically check it with the instructions from the description. Anyways it doesn't make sense trying to check for windows checksum with the standard ubuntu way.

It would be great if someone with windows system could download [windows artifacts from my local branch action run](https://github.com/jxdv/universal-android-debloater/actions/runs/8051205900) and check if it works.

**Comment by AnonymousWP** [comment]
What do you exactly want me to check? I downloaded the release binary and this is in the textfile as checksum:

image

**Comment by jxdv** [comment]
> What do you exactly want me to check? I downloaded the release binary and this is in the textfile as checksum:

I thought windows had a similar way to check the checksums such as in UNIX with the commands listed in the description, but I didn't find anything online, and since the checksums match everything is okay.

Is there any way to do a test release to see if everything works correctly? I am 99.99% sure that this is going to work, but just to be safe :)

**Comment by Frigyes06** [comment]
> > What do you exactly want me to check? I downloaded the release binary and this is in the textfile as checksum:
> 
> I thought windows had a similar way to check the checksums such as in UNIX with the commands listed in the description, but I didn't find anything online, and since the checksums match everything is okay.
> 
> Is there any way to do a test release to see if everything works correctly? I am 99.99% sure that this is going to work, but just to be safe :)

Not that I know of

**Review by Frigyes06 — APPROVED** [review]
These changes make sense to me. I don't have a way to test them before we release again though.

**Comment by jxdv** [comment]
> These changes make sense to me. I don't have a way to test them before we release again though.

I don't think there's a way to test this besides merging this and creating a new release with these changes applied. This should work flawlessly IMO

**Comment by AnonymousWP** [comment]
> > What do you exactly want me to check? I downloaded the release binary and this is in the textfile as checksum:
> 
> I thought windows had a similar way to check the checksums such as in UNIX with the commands listed in the description, but I didn't find anything online, and since the checksums match everything is okay.
> 
> Is there any way to do a test release to see if everything works correctly? I am 99.99% sure that this is going to work, but just to be safe :)

You can calculate hashes with Windows using PowerShell commands. Is that what you're looking for?

```powershell
Get-FileHash uad-ng-windows.exe
```

**Comment by jxdv** [comment]
> > > What do you exactly want me to check? I downloaded the release binary and this is in the textfile as checksum:
> > 
> > 
> > I thought windows had a similar way to check the checksums such as in UNIX with the commands listed in the description, but I didn't find anything online, and since the checksums match everything is okay.
> > Is there any way to do a test release to see if everything works correctly? I am 99.99% sure that this is going to work, but just to be safe :)
> 
> You can calculate hashes with Windows using PowerShell commands. Is that what you're looking for?
> 
> ```powershell
> Get-FileHash uad-ng-windows.exe
> ```

Nope, I am aware of the fact that you can calculate checksums on windows. We could compare that command to: (on debian-based systems)

```cmd
sha256sum uad-ng-windows.exe
```

I was mostly curious if windows has something similar such as:

```cmd
sha256sum --check uad-ng-windows.exe
```

Which gives you the `OK` response if the hashes match (and if the commands are follow by each other).

**Comment by lavafroth** [comment]
At this point we might as well use `cargo cross` which can be used on a single linux machine to cross compile to multiple platforms. Profit: we have to do the checksum business only once.

**Comment by adhirajsinghchauhan** [comment]
> I was mostly curious if windows has something similar such as:
> 
> ```batchfile
> sha256sum --check uad-ng-windows.exe
> ```
> Which gives you the `OK` response if the hashes match (and if the commands are follow by each other).

Nope. You'd need to be far more verbose:
```ps
(Get-FileHash <file>).Hash -eq (Get-Content <checksum-file>)
```
Which would return `True` or `False`. Note that unlike *nix where the checksum(s) file would have a format of `<hash> *file`, `<checksum-file>`'s contents would need to be the hash and only that. This makes it more complicated to check for multiple files at once.

**Comment by jxdv** [comment]
> Nope. You'd need to be far more verbose:
> 
> ```postscript
> (Get-FileHash <file>).Hash -eq (Get-Content <checksum-file>)
> ```
> 
> Which would return `True` or `False`. Note that unlike *nix where the checksum(s) file would have a format of `<hash> *file`, `<checksum-file>`'s contents would need to be the hash and only that. This makes it more complicated to check for multiple files at once.

Well, than from my understanding it seems that windows doesn't really have one standardized way to do this, therefore there are X ways to verify the checksum, and we can have N ways to format `<checksum-file>` for windows. In the end if the windows user wants to verify the checksum he'll get it done.

I also like an approach of having just binary artifacts and one `<checksums>` file where each line has the following structure: `<binary-name> <binary-checksum>`, but again than we lose the standard way for *nix systems to do the verification.

From my POV there isn't 1 best way to do this - it all depends on which approach the project maintainers like the most.

**Comment by AnonymousWP** [comment]
> At this point we might as well use `cargo cross` which can be used on a single linux machine to cross compile to multiple platforms. Profit: we have to do the checksum business only once.

Isn't this the best solution then? We need to automate it as much as possible, but why including a tool with the release? Why not just something like what Microsoft does (automatically calculating the hash and users can then compare it the calculation they can perform themselves):

- https://github.com/microsoft/PowerToys/releases/tag/v0.78.0
- https://github.com/microsoft/terminal/releases/tag/v1.19.10573.0

I think users who want to verify the hash can perfectly do that themselves. 🙂

**Pull request merged**
