### PR TITLE
feat: remove glow feature

### PR DESCRIPTION
**Pull request by B0ney**
**Currently marking this as a draft since this breaks CI, and I'm not good with GitHub actions.**

Iced ``0.10.0`` has removed the ``glow`` rendering backend. Compiling with ``--features=glow`` doesn't do anything but increase compilation times.

``0.10.0`` now includes a software renderer; by setting the environment variable ``ICED_BACKEND=tiny-skia``, the iced runtime will use the software renderer at startup.

Alternatively, disabling iced's ``wgpu`` feature also achieves this.

I'm thinking I could also tweak ``cargo.toml`` to make the following changes:
* ``wgpu = []`` -> ``wgpu = ["iced/wgpu]``
* Add ``default-features=false`` to iced crate

Should that be in a different pr?

### CODE REVIEW

**Comment by Frigyes06** [comment]
@B0ney Is this ready for review?

**Comment by B0ney** [comment]
> @B0ney Is this ready for review?

sure

**Comment by adhirajsinghchauhan** [comment]
I know absolutely nothing about graphic backends. I didn't even know `glow` was removed, as that's not in iced's release notes I believe; nor docs.

What does `iced` use as default if glow does not exist anymore? What would be better to use, wgpu or tiny-skia?

**Comment by B0ney** [comment]
> I know absolutely nothing about graphic backends. I didn't even know `glow` was removed, as that's not in iced's release notes I believe; nor docs.
> 
> What does `iced` use as default if glow does not exist anymore? What would be better to use, wgpu or tiny-skia?

By default, iced uses ``wgpu``.

Personally, I think we should default to ``tiny-skia`` for the following reasons:
* Better hardware support - ``wpgu`` doesn't run as well on older/low end hardware and the GL backend is not as polished. ``tiny-skia`` should provide similar, if not, better support than opengl since it's just software rendering.
* Smaller memory footprint - On my system, it uses ~6MB of memory compared to ~80MB (vulkan backend).
* Smaller binary size (when ``wgpu`` is disabled at crate level) - This becomes more apparent when compiled on Linux.

Cons:
* ``tiny-skia`` is very, **VERY** slow when compiled in debug mode
* Not as battle tested, so it may have some bugs. See https://github.com/iced-rs/iced/issues/2173

**Comment by AnonymousWP** [comment]
@Universal-Debloater-Alliance/developers Please follow-up on this so we can merge this PR.

**Review by lavafroth — APPROVED** [review]
Since the software renderer is quite unstable, let's stick with the Vulkan `wgpu` renderer for now.

**Pull request merged**
