### PR TITLE
pkg(samsung): alt names, missing packs, `fmt` list

### LINKED ISSUE #554: pkg(`com.google.android.overlay.gmsconfig.photos`): it's also installed on Samsung Galaxy devices
### List your packages

- Package name: com.google.android.overlay.gmsconfig.photos
- Current list: Google
  - Proposed list: Google
- Current removal: Recommended
  - Proposed removal: Recommended
- Current description: "overlay to\nconfig_systemGallery to com.google.android.apps.photos in motorola. Useless."
  - Proposed description: "overlay to\nconfig_systemGallery to com.google.android.apps.photos in Motorola. It's also installed on some Samsung Galaxy devices. Useless."

### Acknowledgements

- [X] This issue is not a duplicate of an existing one.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by Rudxain**
closes #554

This PR:
- improves descriptions by adding alternative names
- adds previously-unlisted packages
- formats the JSON

### CODE REVIEW

**Comment by Rudxain** [comment]
I've just noticed my JSON LSP auto-formatted the file 💀

**Comment by Rudxain** [comment]
I've just noticed my JSON LSP auto-formatted the file 💀. The Huawei stuff should've stayed intact. I'm sorry

**Comment by Rudxain** [comment]
As a follow-up to 0x192/universal-android-debloater#811, I've found these unlisteds:
```
com.samsung.android.mdagent
com.samsung.android.wifi.p2paware.resources
com.samsung.phone.overlay.common
```

I'll try to find info about them, so that they can be properly documented

**Comment by AnonymousWP** [comment]
I'll review it once you've solved conflicts.

**Comment by Rudxain** [comment]
GH suggests `git merge main` should I `git rebase -i main` instead?

**Comment by AnonymousWP** [comment]
A `git merge` will do, yes. You just need to merge main into `docs/pkg/SM-A315G`. Git will then tell/show you that there are merge conflicts. Solve them accordingly and commit - resulting in solved conflicts. Make sure you don't throw away the wrong entries though.

**Comment by Rudxain** [comment]
BTW, I had MdAgent uninstalled for **~1 year**, and didn't notice anything wrong. That's why it's `Advanced` rather than `Expert`, despite the lack of info

**Review by AnonymousWP — APPROVED** [review]
Excellent, thanks. 🙂

**Pull request merged**
