### PR TITLE
feat: graphically display error when adb command fails

### PR DESCRIPTION
**Pull request by lavafroth**
This is more or less scaffold code to display the raw error if an ADB command fails.
Related to #37
- We use an enum to classify these errors. Currently it only has one error type as `Generic`.
- Any ADB error will display a modal with the raw error trace of the ADB command itself. 

Screenshot from 2024-04-05 19-25-56

### CODE REVIEW

**Comment by AnonymousWP** [comment]
Could you please include a screenshot for references? Then we can also give feedback about that.

**Comment by adhirajsinghchauhan** [comment]
I'm busy, so I'll let other devs review this

**Comment by AnonymousWP** [comment]
This can't be merged though due to failing checks.

**Review by Frigyes06 — APPROVED** [review]
Nice work, please add more comments next time :)

**Pull request merged**
