### PR TITLE
refactor: use if-let binding for getting package attributes

### PR DESCRIPTION
**Pull request by lavafroth**
### Changes
- Use `if let` binding to get a package if it exists in the list and further access attributes
- No user facing changes

### CODE REVIEW

**Review by Frigyes06 — COMMENTED** [review]
What happens if a package's description is empty?

**Comment by lavafroth** [comment]
The default value is set 2 lines earlier. I just removed the repetition.

**Review by Frigyes06 — APPROVED** [review]

**Comment by Frigyes06** [comment]
@lavafroth Would you be interested in becoming a member of the dev team?

**Comment by lavafroth** [comment]
@Frigyes06 Sure thing!

**Pull request merged**
