### PR TITLE
refactor(program): make UAD-NG list have key value pair for directly building hashmap

### PR DESCRIPTION
**Pull request by lavafroth**
### Changes
- The package struct no longer contains a redundant `id` field
- A hashmap of `id` and package details can be built directly using `serde_json` without allocating an intermediate vector
- As a side effect, deduplication in the JSON file can be performed statically

### CODE REVIEW

**Review by adhirajsinghchauhan — APPROVED** [review]
LGTM except I haven't reviewed `uad_lists.json` at all. Too big.

**Comment by adhirajsinghchauhan** [comment]
@lavafroth There are conflicts to `uad_lists.json`, so we're not merging this PR right now.
I'd recommend resetting that file from `main`, then redoing your changes, and amend both commits.

**Comment by lavafroth** [comment]
Yep. We should probably merge any existing changes to the list, I'll apply the key value conversion then.

**Comment by adhirajsinghchauhan** [comment]
We'll need to coordinate while doing this, because the list is updated quite often by @Universal-Debloater-Alliance/package-contributors.

**Comment by lavafroth** [comment]
Should I convert this PR into a draft for now?

**Comment by lavafroth** [comment]
I'm not going to join the discord but let me know once we temporarily halt the PRs related to the list. I'll redo the conversion then.
no discordo lol

**Comment by AnonymousWP** [comment]
> I'm not going to join the discord but let me know once we temporarily halt the PRs related to the list. I'll redo the conversion then.
> no discordo lol

You're free to suggest alternatives. :)

**Comment by Frigyes06** [comment]
> I'm not going to join the discord but let me know once we temporarily halt the PRs related to the list. I'll redo the conversion then.
> no discordo lol

Do you use matrix? I could set up a bridged channel

**Comment by lavafroth** [comment]
@Frigyes06 yes I'm on matrix.

**Comment by AnonymousWP** [comment]
@Frigyes06 If you have time, please create the Matrix bridge so we can communicate across devs.

**Comment by Frigyes06** [comment]
@lavafroth

Channel: https://matrix.to/#/!EeJLFeBCanmoucRhfO:matrix.org?via=matrix.org

Space:
https://matrix.to/#/#uad-ng:matrix.org

**Review by adhirajsinghchauhan — DISMISSED** [review]

**Review by adhirajsinghchauhan — DISMISSED** [review]

**Comment by adhirajsinghchauhan** [comment]
^ Rebased & re-applied the conversion

**Comment by lavafroth** [comment]
Thanks a lot!

**Pull request merged**
