### PR TITLE
Update uad_lists.json

### PR DESCRIPTION
**Pull request by bornasalman**

### CODE REVIEW

**Comment by AnonymousWP** [comment]
@bornasalman What are you trying to do here? You keep opening and closing PRs.

**Comment by bornasalman** [comment]
> @bornasalman What are you trying to do here? You keep opening and closing PRs.

What?

**Comment by AnonymousWP** [comment]
@bornasalman You are opening pull requests but then close them. Why are you doing that?

**Comment by bornasalman** [comment]
> @bornasalman You are opening pull requests but then close them. Why are you doing that?

Why do people normally pull request?

**Comment by bornasalman** [comment]
Apologies for the above.

**Pull request closed without merging**
