### PR TITLE
chore(issue-templates): improve default title text

### PR DESCRIPTION
**Pull request by AnonymousWP**
This is an attempt to streamline issue titles for in the future, that will hopefully be followed by (future) contributors. If you have a different stance/opinion about this, let's discuss it here.

### CODE REVIEW

**Comment by adhirajsinghchauhan** [comment]
Could add `(scope)` suffix to `bug` and `feat` for an intended use similar to `feat(settings)` or `bug(windows)` etc.

**Comment by Frigyes06** [comment]
> Could add `(scope)` suffix to `bug` and `feat` for an intended use similar to `feat(settings)` or `bug(windows)` etc.

I would love to have predefined scopes for easy standardization

**Comment by AnonymousWP** [comment]
> Could add `(scope)` suffix to `bug` and `feat` for an intended use similar to `feat(settings)` or `bug(windows)` etc.

I initially planned that, but I remember from another repo I manage that a lot of users don't stick to it, e.g. they keep the "scope" part intact and just start writing the title.

What do you think? We can try and see if that's also the case within this repo, or we can keep it like this.

**Comment by AnonymousWP** [comment]
Fair enough - done.

**Review by adhirajsinghchauhan — APPROVED** [review]

**Pull request merged**
