### PR TITLE
feat: add logo to taskbar and window

### PR DESCRIPTION
**Pull request by Frigyes06**

### CODE REVIEW

**Review by AnonymousWP — CHANGES_REQUESTED** [review]
This only adds the image, but doesn't add it to UAD-ng as logo.

**Comment by Frigyes06** [comment]
> This only adds the image, but doesn't add it to UAD-ng as logo.

Yeah. It's the first step to adding the logo. I currently don't have time to implement the code.

**Review by AnonymousWP — CHANGES_REQUESTED** [review]
The background needs to be made transparent first.

**Comment by Frigyes06** [comment]
@AnonymousWP Love and kisses
Also this will look shit on light mode users' desktops

**Comment by adhirajsinghchauhan** [comment]
^ only applies the icon to the application window, not to the executable itself:
image

So it won't show in file explorer:
image

On Windows 11, it also shows up on taskbar but I'm not sure about other OSes:
image

**Comment by adhirajsinghchauhan** [comment]
To attach it to the executable, we'll need a custom build script and additional crates, like [winres](https://docs.rs/winres) for Windows.

**Comment by Frigyes06** [comment]
I don't think having it on the executable is important enough to include nore deps and code

**Comment by adhirajsinghchauhan** [comment]
> I don't think having it on the executable is important enough to include nore deps and code

Agreed, but we'll still need someone to verify appearance on Linux (preferably several distros) and Mac before we can merge this PR.

**Comment by Frigyes06** [comment]
KDE taskbar:
image

KDE Window:
image

**Review by adhirajsinghchauhan — APPROVED** [review]

**Comment by Rudxain** [comment]
We can emulate an icon for the executable by using a [`.desktop` file](https://specifications.freedesktop.org/desktop-entry-spec/latest/). I'll open a PR for this

**Pull request merged**
