### PR TITLE
feat(ui): change default theme to Dark

### LINKED ISSUE #122: Change default theme from `Lupin` to `Dark`
**Describe the feature you want**
Default theme should be `Dark` and not `Lupin`.

### PR DESCRIPTION
**Pull request by Frigyes06**
Fixes #122

### CODE REVIEW

**Comment by adhirajsinghchauhan** [comment]
It's important to remember that only 4 people (so far, out of 5) have voted "Yes" on https://github.com/Universal-Debloater-Alliance/universal-android-debloater/discussions/123.

I don't mind either dark or lupin, but I'm not sure if we need to change the default just because a very small amount of people like it better.

We can keep this PR open until we see significant number of votes. There's loads of people whose opinions we haven't considered, because they haven't yet seen the poll yet (and maybe never will? I don't know where it was posted first).

**Comment by Frigyes06** [comment]
Yep, I'm waiting for consensus. Just made the PR so it's ready if ppl want it. I can convert to draft in the meantime

**Comment by AnonymousWP** [comment]
Don't think we're getting more than the amount of votes we have now: https://github.com/Universal-Debloater-Alliance/universal-android-debloater/discussions/123

**Comment by lavafroth** [comment]
Looks like @0x192 never really used the secondary colors, making everything other than Lupin look terrible. Here's a dark theme I created with [realtime colors](https://www.realtimecolors.com/?colors=f4e6f4-1b0a1c-dc99dd-782379-d35ad5) [in this branch](https://github.com/lavafroth/universal-android-debloater/tree/better-dark).

Screenshot_20240102_160013

**Comment by lavafroth** [comment]
Update: these are the themes after some refactoring, vaguely following material UI guidelines. I'm pretty happy with how they've turned out. Let me know if you want to land these into main.

**Comment by adhirajsinghchauhan** [comment]
@lavafroth contrast needs some work. At a bare minimum, WCAG AA must pass for all sizes: https://webaim.org/resources/contrastchecker/, and ideally AAA as well.

Also let the light & dark themes' backgrounds remain standard: white & dark gray. Colourful backgrounds aren't really suited for desktop applications.

Lupin can be anything, but as it's also a dark theme, background should be more muted. It shouldn't jump out at you and be an eyesore (which is what it is for me at least).

You can play around and create a PR if you want, but we probably won't merge anything until we figure out a palette ourselves.
Personally, I now want to ditch Lupin altogether, because I foresee feature requests for pretty much all popular themes: monokai, dracula, solarized, etc.

**Comment by lavafroth** [comment]
Yeah, I wish there was some OS agnostic accent color API that I could pull colors from.

**Comment by lavafroth** [comment]
Update: I've been working on an alternative UI for our project using egui [here](https://github.com/lavafroth/distillery). This is very alpha taking around 2 hours (including me learning egui for the first time).

**Comment by AnonymousWP** [comment]
@lavafroth Do you plan on using that alternative UI for this PR? If so, any updates on this?

**Comment by lavafroth** [comment]
Let's keep the current dark theme for now. I'd need to make the alternate UI a little more accessible.

**Review by lavafroth — APPROVED** [review]

**Pull request merged**
