### PR TITLE
Description updates with source code. JSON Sort + Prettify.

### PR DESCRIPTION
**Pull request by bornasalman**
+VSCode built-in JSON Sort
+VSCode built-in JSON Prettify (Alt+Shift+F)
+Updated package descriptions with source code

### CODE REVIEW

**Comment by bornasalman** [comment]
@AnonymousWP This is why. The notifications shouldn't be that much of a bother when people are trying to contribute.

**Comment by bornasalman** [comment]
Package changes on their own should you not want to make such a big change, though better now than later. I liked it better before with separate files for OEM, AOSP, etc. before, to be honest.

```
{
    "android": {
        "dependencies": [],
        "description": "Android\nhttps://android.googlesource.com/\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Unsafe"
    },
    "android.auto_generated_rro_product__": {
        "dependencies": [],
        "description": "Android Auto-generated Product Runtime Resource Overlay\nRemoving may cause battery drain.\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "android.auto_generated_rro_vendor__": {
        "dependencies": [],
        "description": "Android Auto-Generated Vendor Runtime Resource Overlay\nRemoving may cause battery drain.\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "android.autoinstalls.config.samsung": {
        "dependencies": [],
        "description": "Samsung Auto-Installs Layout\nAuto-installs layout parser.\nhttps://android.googlesource.com/platform/packages/apps/Launcher3/+/android-14.0.0_r18/src/com/android/launcher3/AutoInstallsLayout.java\n",
        "labels": [],
        "list": "Oem",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.apps.tag": {
        "dependencies": [],
        "description": "Tag Viewer\nHandles broadcast of a new tag.\nhttps://android.googlesource.com/platform/packages/apps/Tag/+/master/src/com/android/apps/tag/TagViewer.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Advanced"
    },
    "com.android.backupconfirm": {
        "dependencies": [],
        "description": "Backup/Restore confirmation\nUI that confirms with user that a requested full backup/restore operation is legitimate.\nhttps://android.googlesource.com/platform/frameworks/base/+/cd92588/packages/BackupRestoreConfirmation/src/com/android/backupconfirm/BackupRestoreConfirmation.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.bips": {
        "dependencies": [],
        "description": "Built-In Print Service\nhttps://android.googlesource.com/platform/packages/services/BuiltInPrintService/+/refs/heads/main/src/com/android/bips\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Advanced"
    },
    "com.android.bluetooth": {
        "dependencies": [],
        "description": "Bluetooth\nhttps://android.googlesource.com/platform/packages/apps/Bluetooth/+/3751015/src/com/android/bluetooth\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Unsafe"
    },
    "com.android.bluetoothmidiservice": {
        "dependencies": [],
        "description": "Bluetooth MIDI Service\nImplements Bluetooth MIDI devices.\nhttps://android.googlesource.com/platform/frameworks/base/+/f0a41d1/media/packages/BluetoothMidiService/src/com/android/bluetoothmidiservice/BluetoothMidiDevice.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Advanced"
    },
    "com.android.bookmarkprovider": {
        "dependencies": [],
        "description": "Bookmark Provider\nExists only to prevent querying null cursor crashes.\nhttps://android.googlesource.com/platform/packages/providers/BookmarkProvider/+/master/src/com/android/bookmarkstore/BookmarkProvider.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.calllogbackup": {
        "dependencies": [],
        "description": "Call Log Backup\nTriggers backup accordingly when call log provider changes.\nhttps://android.googlesource.com/platform/packages/providers/CallLogProvider/+/349e0f4/src/com/android/calllogbackup/CallLogChangeReceiver.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.cameraextensions": {
        "dependencies": [],
        "description": "Camera Extensions Proxy Service\nPer-process camera extension manager instance to track and initialize/release extensions depending on client activity.\nAlso checks camera extensions for outdated APIs.\nhttps://android.googlesource.com/platform/prebuilts/fullsdk/sources/android-31/+/refs/heads/androidx-camera-release/com/android/cameraextensions/CameraExtensionsProxyService.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.carrierconfig": {
        "dependencies": [],
        "description": "Default Carrier Config Service\nProvides network overrides for carrier configuration.\nhttps://android.googlesource.com/platform/packages/apps/CarrierConfig/+/master/src/com/android/carrierconfig/DefaultCarrierConfigService.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.carrierdefaultapp": {
        "dependencies": [],
        "description": "Carrier Default App\nAllows carrier customization. OEMs could configure a list of carrier actions defined to act upon signals. Allows different interpretations of signals between carriers and could alter an app's behaviour in a configurable way.\nhttps://android.googlesource.com/platform/frameworks/base/+/master/packages/CarrierDefaultApp/src/com/android/carrierdefaultapp/CustomConfigLoader.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.certinstaller": {
        "dependencies": [],
        "description": "Cert Installer\nInstalls certificates to the system keystore.\nhttps://android.googlesource.com/platform/packages/apps/CertInstaller/+/83df03c8f5d61d37e2fda501c67937f970b7af0c/src/com/android/certinstaller/CertInstaller.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.chrome": {
        "alternatives": "Brave Browser (Nightly)",
        "dependencies": [],
        "description": "Chrome\nPreinstalled browser.\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Recommended"
    },
    "com.android.companiondevicemanager": {
        "dependencies": [],
        "description": "Companion Device Manager\nSystem level service for managing companion devices through given WiFi MAC address or BSSID.\nhttps://android.googlesource.com/platform/prebuilts/fullsdk/sources/android-30/+/refs/heads/androidx-biometric-release/android/companion/CompanionDeviceManager.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.credentialmanager": {
        "dependencies": [],
        "description": "Credential Manager\nStores credentials and provides autofill service.\nhttps://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/CredentialManager/src/com/android/credentialmanager?hl=ko%2F%2F%2F%2F&autodive=0%2F%2F%2F%2F%2F\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.cts.ctsshim": {
        "dependencies": [],
        "description": "CTS Shim\nVerifies certain upgrade scenarios.\nhttps://android.googlesource.com/platform/frameworks/base/+/51e458e/packages/CtsShim/build/README\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.cts.priv.ctsshim": {
        "dependencies": [],
        "description": "CTS Shim\nVerifies certain upgrade scenarios.\nhttps://android.googlesource.com/platform/frameworks/base/+/51e458e/packages/CtsShim/build/README\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.dreams.basic": {
        "dependencies": [],
        "description": "Basic\nInteractive colours screen saver.\nhttps://android.googlesource.com/platform/packages/screensavers/Basic/+/jb-mr1-release/src/com/android/dreams/basic/Colors.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Advanced"
    },
    "com.android.dreams.phototable": {
        "dependencies": [],
        "description": "Photo Table\nInteractive photo table screen saver.\nhttps://android.googlesource.com/platform/packages/screensavers/PhotoTable/+/e8f4d55/src/com/android/dreams/phototable/PhotoTable.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Advanced"
    },
    "com.android.dynsystem": {
        "dependencies": [],
        "description": "Dynamic System Installation Service\nDynamicSystem installation service.\nIt also posts status to notification bar and waits for user cancel/confirm command.\nhttps://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/DynamicSystemInstallationService/src/com/android/dynsystem/DynamicSystemInstallationService.java\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Expert"
    },
    "com.android.egg": {
        "dependencies": [],
        "description": "Android Easter Egg\nhttps://android.googlesource.com/platform/frameworks/base/+/172efa1/packages/EasterEgg/src/com/android/egg/paint?autodive=0%2F\n",
        "labels": [],
        "list": "Aosp",
        "neededBy": [],
        "removal": "Recommended"
    }
```

**Comment by AnonymousWP** [comment]
Thanks for your PR. Can you please split-up your PR? We'd like the package descriptions in a separate PR.

**Comment by Frigyes06** [comment]
Yeah, the sort and the desc changes need to be separate so we can review them easily. Thanks for your efforts!

**Pull request closed without merging**
