### PR TITLE
chore(release): preparation for v1.1.0

### PR DESCRIPTION
**Pull request by Frigyes06**

### CODE REVIEW

**Comment by AnonymousWP** [comment]
We should:

- Rebase this PR before testing
- Test build with new deps before release

**Comment by Frigyes06** [comment]
It builds & runs, basic functions work, no issues observed

**Comment by AnonymousWP** [comment]
Converting this to a draft until https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/550 is fixed. When it's fixed, dependencies need to be updated again (there could be new versions in 5 days time).

**Comment by Rudxain** [comment]
> until #550 is fixed

I'm unsure if that's necessary 🤔. We could fix the bug after the release, it's not a big deal, we already have a "Minimum Viable Product"

**Comment by AnonymousWP** [comment]
But by the looks of it, when the bug occurs, it's a bug that may confuse users. I prefer having it in the 1.1.0 release.

**Review by AnonymousWP — APPROVED** [review]

**Pull request merged**
