### PR TITLE
pkg: sort and prettify uad_lists.json

### PR DESCRIPTION
**Pull request by bornasalman**
+VSCode built-in JSON Sort
+VSCode built-in JSON Prettify (Alt+Shift+F)

### CODE REVIEW

**Comment by bornasalman** [comment]
Sorry, I wasn't able to commit to the previous PR. It auto-closed after I deleted my commits.

**Comment by Blitz517** [comment]
I dont like sorting JSON when this lists looks already good to know on which is old or new by line number.

**Comment by bornasalman** [comment]
> I dont like sorting JSON when this lists looks already good to know on which is old or new by line number.

That's fair. My only real counter is that it's a pain to debloat through the unsorted JSON when I don't have access to UAD in full. A lot of times I'll just reference the JSON and debloat on-device.

I will say it wouldn't be too hard to pull package lists for each of the past few OEM devices and remove anything that isn't on the list. I saw somebody trying to update some One UI 2.5 stuff in a description, would be worth considering a cut-off or EOS for that sort of thing.

**Comment by AnonymousWP** [comment]
> My only real counter is that it's a pain to debloat through the unsorted JSON when I don't have access to UAD in full. A lot of times I'll just reference the JSON and debloat on-device.

Why? What do you mean "UAD in full"? You can just clone it locally, then ctrl F. I'm also not sure if your refactor will sort it inside UAD-ng itself. 🤔

> I will say it wouldn't be too hard to pull package lists for each of the past few OEM devices and remove anything that isn't on the list. I saw somebody trying to update some One UI 2.5 stuff in a description, would be worth considering a cut-off or EOS for that sort of thing.

Does it really matter though? The list is only 1.29MB.

**Comment by bornasalman** [comment]
UAD-ng itself sorts by package label. 
And I agree, if the file size doesn't matter then I don't see the significance of very rough chronology.

Here's what I'm getting at when I say UAD is a resource outside of the software too:

<details>
Screenshot_20240529_170516_Brave - Nightly
</details>
<details>
Screenshot_20240529_170424_App Manager
</details>
<details>
Screenshot_20240529_170516_Brave - Nightly
</details>

**Comment by AnonymousWP** [comment]
Even though I appreciate your effort, I do not see any benefit of it (ctrl F exists anyway). Also because it will always conflict with a package PR.

**Pull request closed without merging**
